Fix CS0023: Use explicit Enumerable.Reverse() call in ProductKeyValidator
Changed from .Reverse() extension method to Enumerable.Reverse() static method
to avoid ambiguity with other Reverse implementations. This resolves the CS0023
compilation error on line 191.

File: ProductKeyValidator.cs:191
Error: Operator '.' cannot be applied to operand of type 'void'
Solution: Use System.Linq.Enumerable.Reverse() explicitly