Fix CS1061: Use correct HashSet.SymmetricExceptWith method
HashSet<T> does not have a 'SymmetricExceptDifference' method. The correct
method is 'SymmetricExceptWith', which modifies the set in-place.

Changed to create a copy of oldStepIds, call SymmetricExceptWith on it,
then get the count of the resulting symmetric difference.

File: GuideEngine.cs:398
Error: 'HashSet<string>' does not contain a definition for 'SymmetricExceptDifference'
Solution: Use SymmetricExceptWith (void method) on a copy of the HashSet